; ==========================================================================
; ACIA interrupt test — enable MC68B50 RX interrupts and wait in HALT
; ==========================================================================
; The reset vector and IM 1 handler live in a separate ROM image generated by
; make_acia_irq_rom.py.  This program is loaded at Z80 RAM address 0x2000.
;
; The ROM handler explicitly reads ACIA data port 0x81, then echoes the byte
; through the ACIA after polling TDRE.  Keeping the data read in the handler
; verifies that RX is not prefetched by the interrupt acknowledge cycle.
;
; No .org directive is used: assemble_z80.py's linker origin supplies 0x2000.
; ========================================================================

start:
    ; Select a normal ACIA mode first.  CR[1:0]=11 is divide-by-1 in the
    ; bridge's MC68B50-compatible control model; RX IRQ is still disabled.
    ld a, 03h
    out (80h), a

    ; Enable receive interrupts (CR[7]) with RX IRQ only (CR[6:5]=00).
    ; CR[4:2]=101, CR[1:0]=11 => 0x97.
    ld a, 97h
    out (80h), a

    im 1
    ei

wait_for_interrupt:
    halt                    ; ACIA IRQ wakes the CPU and vectors to 0038h
    jr wait_for_interrupt

end:
    jr end
