#!/usr/bin/env bash
# Build the SD image and LIVE-UPDATE the EBAZ4205 board (no rootfs replace).
#
# Usage:
#   ./scripts/ebaz_deploy.sh                # make sdimg + live-update ${EBAZ_HOST:-ebaz}
#   ./scripts/ebaz_deploy.sh --skip-build   # deploy existing build_sdimg/ artifacts
#   ./scripts/ebaz_deploy.sh --no-modules   # skip the /lib/modules sync (pure HDL cycle)
#   ./scripts/ebaz_deploy.sh --bitstream-only              # build + full PL reload, no reboot
#   ./scripts/ebaz_deploy.sh --bitstream-only --skip-build # reload build_sdimg bitstream only
#   ./scripts/ebaz_deploy.sh root@192.168.1.203
#
# Live update (default) never touches SD partition 2 (the rootfs):
#   1. make sdimg                     -> build_sdimg/ (BOOT.bin, uImage, dtb, dtbo, bitstream)
#   2. scp -O the 6 boot files to <host>:/mnt/   (boot partition; SFTP missing -> -O)
#   3. sync the kernel module tree over ssh: tar lib/modules/<kver>/ (incl.
#      modules.dep/modules.alias generated by the build) -> board /lib/modules/.
#      The board has NO depmod (busybox CONFIG_DEPMOD off, kmod-tools off), so
#      the whole tree must come from the build machine, not just the .ko files.
#   4. sync + reboot
#   5. wait for it to come back (ping loop, then sshd poll) and print uname
#
# Full rootfs replace is a SEPARATE workflow, only for rootfs *userspace*
# changes (busybox config, packages, inittab) or to resync a drifted board:
# attach the SD card to this machine and run scripts/flash_rootfs.sh <device>.
# Never dd over the rootfs of a running board.

set -euo pipefail

HOST="${EBAZ_HOST:-ebaz}"
SKIP_BUILD=0
SYNC_MODULES=1
BITSTREAM_ONLY=0

for arg in "$@"; do
  case "$arg" in
    --skip-build) SKIP_BUILD=1 ;;
    --no-modules) SYNC_MODULES=0 ;;
    --bitstream-only) BITSTREAM_ONLY=1 ;;
    -h|--help)
      grep '^#' "$0" | grep -v '^#!/' | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    -*) echo "unknown option: $arg" >&2; exit 1 ;;
    *) HOST="$arg" ;;
  esac
done

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
SDIMG="$ROOT/build_sdimg"
MODSRC="$ROOT/buildroot/output/target/lib/modules"

FILES=(BOOT.bin boot.scr devicetree.dtb pl-ebaz4205.dtbo system_top.bit.bin uImage)  # boot partition (/mnt/)

# A bitstream-only deployment is a full PL reconfiguration, not a reboot and
# not partial reconfiguration.  The active configfs overlay is removed first
# so Linux unbinds its PL drivers, then restored after fpgautil programs the
# FPGA.  The dedicated Ethernet PHY oscillator keeps SSH alive throughout.
if [ "$BITSTREAM_ONLY" -eq 1 ]; then
  if [ "$SKIP_BUILD" -eq 0 ]; then
    echo "==> make build/system_top.bit.bin ..."
    (cd "$ROOT" && make build/system_top.bit.bin)
    BITSTREAM="$ROOT/build/system_top.bit.bin"
  else
    BITSTREAM="$SDIMG/system_top.bit.bin"
    if [ ! -f "$BITSTREAM" ]; then
      BITSTREAM="$ROOT/build/system_top.bit.bin"
    fi
  fi

  [ -f "$BITSTREAM" ] || {
    echo "missing bitstream ($BITSTREAM) -- run without --skip-build" >&2
    exit 1
  }
  echo "    bitstream: $BITSTREAM ($(du -h "$BITSTREAM" | cut -f1))"

  echo "==> Checking board $HOST is online ..."
  ssh -o BatchMode=yes -o ConnectTimeout=10 "$HOST" 'echo "    board ok: $(uname -n) $(uname -r)"' || {
    echo "board $HOST not reachable before deploy" >&2
    exit 1
  }

  echo "==> Copying bitstream to $HOST:/mnt/system_top.bit.bin ..."
  scp -O -o ConnectTimeout=10 "$BITSTREAM" "$HOST":/mnt/system_top.bit.bin

  echo "==> Reprogramming PL and reapplying the device-tree overlay (no reboot) ..."
  ssh -o BatchMode=yes -o ConnectTimeout=10 "$HOST" '
    set -eu
    OVERLAY_DIR=/sys/kernel/config/device-tree/overlays/pl
    OVERLAY_FILE=/mnt/pl-ebaz4205.dtbo
    BITSTREAM=/mnt/system_top.bit.bin

    if [ -d "$OVERLAY_DIR" ]; then
      echo "    removing active PL overlay ..."
      if ! rmdir "$OVERLAY_DIR"; then
        echo "cannot remove $OVERLAY_DIR; close users of PL devices and retry" >&2
        exit 1
      fi
    fi

    echo "    programming full bitstream ..."
    fpgautil -b "$BITSTREAM" -f Full

    echo "    applying PL overlay ..."
    mkdir -p "$OVERLAY_DIR"
    if ! cat "$OVERLAY_FILE" > "$OVERLAY_DIR/dtbo"; then
      rmdir "$OVERLAY_DIR" 2>/dev/null || true
      echo "cannot apply $OVERLAY_FILE" >&2
      exit 1
    fi
    sync
    echo "    FPGA state: $(cat /sys/class/fpga_manager/fpga0/state 2>/dev/null || echo unknown)"
  '

  echo "==> Done. Bitstream is active; the board was not rebooted."
  exit 0
fi

if [ "$SKIP_BUILD" -eq 0 ]; then
  echo "==> make sdimg ..."
  (cd "$ROOT" && make sdimg)
fi

echo "==> Verifying artifacts ..."
for f in "${FILES[@]}"; do
  [ -f "$SDIMG/$f" ] || { echo "missing $SDIMG/$f (run without --skip-build)" >&2; exit 1; }
  echo "    $f ($(du -h "$SDIMG/$f" | cut -f1))"
done

if [ "$SYNC_MODULES" -eq 1 ]; then
  if [ -d "$MODSRC" ]; then
    MKVER="$(ls "$MODSRC" | head -1)"
    echo "    kernel modules: lib/modules/$MKVER ($(du -sh "$MODSRC/$MKVER" | cut -f1)) -- synced live to /lib/modules/"
  else
    echo "    ERROR: $MODSRC missing -- run 'make sdimg' (or 'make build/rootfs.ext4') first." >&2
    exit 1
  fi
else
  echo "    kernel modules: skipped (--no-modules)"
fi

echo "==> Checking board $HOST is online ..."
ssh -o BatchMode=yes -o ConnectTimeout=10 "$HOST" 'echo "    board ok: $(uname -n) $(uname -r)"' || {
  echo "board $HOST not reachable before deploy" >&2
  exit 1
}

echo "==> Copying boot files to $HOST:/mnt/ ..."
scp -O -o ConnectTimeout=10 "${FILES[@]/#/$SDIMG/}" "$HOST":/mnt/

if [ "$SYNC_MODULES" -eq 1 ]; then
  echo "==> Syncing kernel modules to $HOST:/lib/modules/ ..."
  tar -C "$ROOT/buildroot/output/target" -cf - "lib/modules" \
    | ssh -o BatchMode=yes -o ConnectTimeout=10 "$HOST" 'tar -C / -xf - && sync'
fi

echo "==> Syncing and rebooting ..."
ssh "$HOST" 'sync; reboot' || true   # ssh drops while rebooting; that is expected

IP="$(ssh -G "$HOST" 2>/dev/null | awk '/^hostname /{print $2; exit}')"
IP="${IP:-192.168.1.203}"

echo "==> Waiting for $HOST ($IP) to respond to ping ..."
deadline=$((SECONDS + 180))
while [ $SECONDS -lt $deadline ]; do
  if ping -c 1 -W 1 "$IP" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
if ! ping -c 1 -W 1 "$IP" >/dev/null 2>&1; then
  echo "board did not respond to ping within 180s" >&2
  exit 1
fi

echo "==> ICMP up, waiting for sshd ..."
n=0
until ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new "$HOST" 'true' 2>/dev/null; do
  n=$((n + 1))
  if [ "$n" -ge 60 ]; then
    echo "sshd did not come up within 300s" >&2
    exit 1
  fi
  sleep 5
done

echo "==> Board is back online:"
ssh "$HOST" 'uname -a; ls /mnt/; echo "--- modules ---"; ls /lib/modules/$(uname -r)/kernel/drivers/tty/serial /lib/modules/$(uname -r)/kernel/drivers/staging/axis-fifo 2>/dev/null'
echo "==> Done. (Full rootfs replace, if ever needed: attach SD card here, scripts/flash_rootfs.sh /dev/sdX)"
